import { createClient } from '@supabase/supabase-js'

export const supabase = createClient('https://urovrkaxhpwqgumpqrgs.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVyb3Zya2F4aHB3cWd1bXBxcmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc5NjgyOTIsImV4cCI6MjA1MzU0NDI5Mn0.biABdFXu0JNUH0qDjiny9lCm9riJ8Xuh6ADU1rhhx3g')